[package]
name = "q-learning-tictactoe"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"
iced = { version = "0.12.1", features = ["async-std"] }
serde = { version = "1.0.218" , features = ["derive"]}
serde_json = { version = "1.0.140" }